ALTER TABLE approved_users
ADD COLUMN IF NOT EXISTS kakao_name TEXT,
ADD COLUMN IF NOT EXISTS kakao_nickname TEXT,
ADD COLUMN IF NOT EXISTS profile_image_url TEXT,
ADD COLUMN IF NOT EXISTS message TEXT,
ADD COLUMN IF NOT EXISTS approved_by TEXT,
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE pending_approvals
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS kakao_name TEXT,
ADD COLUMN IF NOT EXISTS kakao_nickname TEXT,
ADD COLUMN IF NOT EXISTS profile_image_url TEXT,
ADD COLUMN IF NOT EXISTS role_requested TEXT DEFAULT 'user',
ADD COLUMN IF NOT EXISTS message TEXT;
